// ops.rs integration tests.
//
// Test integrity rules:
// - Sign -> openssl verify: uses openssl as independent external oracle.
//   The public key is extracted independently of the sign path.
// - Error code tests: assert CKR-equivalent errors for invalid mechanism/key type.
// - NO self-referential round-trips (no wolfcrypt verify after wolfcrypt sign).

use std::io::Write;
use std::process::Command;
use tempfile::NamedTempFile;
use cryptoki_sys::{CKM_ECDSA, CKM_ECDSA_SHA256, CKM_RSA_PKCS_PSS};
use usb_hsm::keystore::{KeyEntry, KeyType};
use usb_hsm::ops::{self, OpsError};

// ---------------------------------------------------------------------------
// Test key material (generated by openssl, embedded here as static data)
// ---------------------------------------------------------------------------

/// 2048-bit RSA private key in PKCS#1 DER format (hex-encoded).
/// Generated with: openssl genrsa 2048 | openssl rsa -outform DER | xxd -p -c 256
const RSA_PKCS1_DER_HEX: &str =
    "308204bc020100300d06092a864886f70d0101010500048204a6308204a2020100\
028201010090bca1c919c80b652bf02db7c6b784ded65262e5f74017109ee13f4\
5e83e7c80a7403ddc9f5ad75ae7260b5dd8e0ce665b32f80f9ce42b015c2f7cd5\
7d94efca1c87d60cc7d2ed86eb74678f5fd99e212b633f069dc94e024a9d2f10d\
0d0466538256d982a00e7eaa268ae0cec20a94f82b3e9fcaa4d4e9c8cf25acd30\
024f85c38a608b54c36d84cc8299ffb6b8bfdb33d1d33de9fdc78c9bfae78d398\
464b1df4676acac3ec505c67a4740b4bfd791454bd31963c2e065f1c33dc459292\
dc5db58a2ebe6a066080c9673fe429fb67a6637e31f3a1f42d90a943390e4c684\
81a97c2dbf8c26be8b93c17f84de66b04b5f66a4c29d67d403f565b0774f0b59c\
70203010001028201000487a135d054a6590cc0167c9bd93b86a3debad1744b0ae\
75b299b57a4dc9efc4e995369848a0cfd990897151488123da072ded20578b56f7\
45ca5506ffed666c83ccee57bb3ed92f6eaeca0cf674046001586c98b1fa873a88\
1f51109c332f59dd2220ea632b00f73f4c8f35395c0e6c80bb93eb4a2f8f4c58b\
4f0733f4f35b25376cc13aa7aab8f8e0084fc7333ba59311f71746f5de4fa86c1f\
1bfcca438063ba7045a3240aa988ff211ccc3123c356464305e0ba9c5f510936df\
e777fedd538ecac8911122f8fe1497f86a265ad870531fcc0e00817a43fd050aa7\
23aba87aa0b2b1bc78130a5910f7ce3ead4f541237da27cfb5758ebb51f4b1606d\
c2ad02818100c816292b3739f2226643bcfa41b31d4259c1e0fa38c4f66bc6e267\
55318a187659c9b46266a95ad547c823e87b7a795e97fff3ee535add2b29e3755d\
f07eb03a8d526e96152ceb4c54634bd9df9550cce0a5554b5f85173a56a26a361\
1d6be491e173b5e9ef96699f17bc65841debae99f3c9f983e83c0add8bb6d73c4c\
36f1502818100b92ed992bccf1787d7cf8231e9d19eda1040140ed74237fe87b72\
4ee515c39c0fa6b590708d4083a65c687f3935479c8bb8cc94bded52f48d55cc46\
dc13b61226927e5f581f560bb437a6e190399f4998b119be57a33fd77e744c50a2\
c65f54e503636fba598be062a1a2e254654692f1581cd9778f48470f95ebca9c2c\
73c6b02818041704e029e4b4b4fc8d67aa5f67ad824ed2a25a47090aa6f515a96a\
51c50a7f37d2624e2d1e4ad9a77a1936ce38588d051321adb6553a0660f8b1ec59\
c7432bad3a1941d6dcb85212fb0520c6dbd6df1b3bf1f0849b3438786f2137e9f\
92f624ffbc65646ae5f292829212aaa6d06b9d20c1390917d90b59503aec6f2279\
30890281807b95999c45274c03db71dfe8a1abc480b121a2813905374b4595632f\
2cdb08ac12337be9a6e9a2481ecdfcc3008afaef8cc2eb4018095c12165a5fb903\
a13634f9caa7bc4dabcd8f8bfbf3e7fbb04e3dfe429530f37a28e9514d62d66444\
f30dfd9800dfb667164214ecfde8e063cb02a22ecb5f1058d6de727dd818cf2599\
db028180343c18d07cb36b8cf0aeaf131737392ca61458bf739144c3dea2df3e9b\
2dcba31228d42d696a3b5dfadcefea8433cd6dac264a916d242c3edee280927d24\
a276933e809bd4512637c5f66bf88d4c7556651fd898244750468276d44339086f\
56ae79d42ff7efb8eba4a2c1aec0e258bfa46ed40aaf5f8fabc4251d72d597941d";

/// RSA 2048-bit public key in PEM format (SubjectPublicKeyInfo, OpenSSL PKCS#8 format).
const RSA_PUB_PEM: &str = "-----BEGIN PUBLIC KEY-----\n\
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkLyhyRnIC2Ur8C23xreE\n\
3tZSYuX3QBcQnuE/Reg+fICnQD3cn1rXWucmC13Y4M5mWzL4D5zkKwFcL3zVfZTv\n\
yhyH1gzH0u2G63Rnj1/ZniErYz8GnclOAkqdLxDQ0EZlOCVtmCoA5+qiaK4M7CCp\n\
T4Kz6fyqTU6cjPJazTACT4XDimCLVMNthMyCmf+2uL/bM9HTPen9x4yb+ueNOYRk\n\
sd9GdqysPsUFxnpHQLS/15FFS9MZY8LgZfHDPcRZKS3F21ii6+agZggMlnP+Qp+2\n\
emY34x86H0LZCpQzkOTGhIGpfC2/jCa+i5PBf4TeZrBLX2akwp1n1AP1ZbB3TwtZ\n\
xwIDAQAB\n\
-----END PUBLIC KEY-----\n";

/// P-256 raw private key scalar (hex-encoded, 32 bytes).
/// Generated with: openssl ecparam -name prime256v1 -genkey | openssl ec -outform DER
/// then the 32-byte scalar extracted from offset 7 of the SEC1 DER.
const EC_PRIV_HEX: &str = "0933c1010f2979cdde48ae7a403a816591e82fcb54fc288e8da637ce4fd570dc";

/// P-256 public key in PEM format matching the private key above.
const EC_PUB_PEM: &str = "-----BEGIN PUBLIC KEY-----\n\
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWRQtnlYv3Adsx0aUHF5xC5saolFi\n\
Cj9KLL55jRVdDwDOm82eSiZtkf+tBwKxRriC2m3vk0DQbH6Cgz7ssHsthg==\n\
-----END PUBLIC KEY-----\n";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn rsa_entry() -> KeyEntry {
    KeyEntry {
        id: [1u8; 16],
        label: "test-rsa".to_owned(),
        key_type: KeyType::Rsa,
        der_bytes: hex::decode(RSA_PKCS1_DER_HEX).expect("rsa hex decode"),
        cert_der: None,
        pub_bytes: None,
    }
}

fn ec_entry() -> KeyEntry {
    KeyEntry {
        id: [2u8; 16],
        label: "test-ec".to_owned(),
        key_type: KeyType::Ec,
        der_bytes: hex::decode(EC_PRIV_HEX).expect("ec hex decode"),
        cert_der: None,
        pub_bytes: None,
    }
}

fn write_tmp(data: &[u8]) -> NamedTempFile {
    let mut f = NamedTempFile::new().expect("tmpfile");
    f.write_all(data).expect("write");
    f
}

fn write_tmp_str(s: &str) -> NamedTempFile {
    write_tmp(s.as_bytes())
}

/// Convert P-256 raw r||s (64 bytes) to DER SEQUENCE { INTEGER r, INTEGER s }.
/// Independent implementation used to present token signatures to openssl,
/// which expects DER. NOT the production rs_to_der in ops.rs.
fn raw_rs_to_der(raw: &[u8]) -> Vec<u8> {
    assert_eq!(raw.len(), 64, "P-256 raw r||s must be 64 bytes");
    let r = &raw[..32];
    let s = &raw[32..];

    fn encode_int(v: &[u8]) -> Vec<u8> {
        let start = v.iter().position(|&b| b != 0).unwrap_or(v.len() - 1);
        let trimmed = &v[start..];
        let mut out = vec![0x02u8];
        if trimmed[0] & 0x80 != 0 {
            out.push(trimmed.len() as u8 + 1);
            out.push(0x00);
        } else {
            out.push(trimmed.len() as u8);
        }
        out.extend_from_slice(trimmed);
        out
    }

    let r_enc = encode_int(r);
    let s_enc = encode_int(s);
    let payload_len = r_enc.len() + s_enc.len();
    let mut der = vec![0x30u8, payload_len as u8];
    der.extend_from_slice(&r_enc);
    der.extend_from_slice(&s_enc);
    der
}

// ---------------------------------------------------------------------------
// Test 1: RSA-PSS sign -> openssl verify
// ---------------------------------------------------------------------------

#[test]
fn rsa_pss_sign_verified_by_openssl() {
    let entry = rsa_entry();
    let msg = b"test message for RSA-PSS";

    let sig = ops::sign(&entry, CKM_RSA_PKCS_PSS, msg).expect("RSA-PSS sign failed");

    let sig_file = write_tmp(&sig);
    let msg_file = write_tmp(msg);
    let pub_file = write_tmp_str(RSA_PUB_PEM);

    // openssl hashes msg with SHA-256 and verifies the PSS signature
    let output = Command::new("openssl")
        .args([
            "dgst", "-sha256",
            "-sigopt", "rsa_padding_mode:pss",
            "-verify", pub_file.path().to_str().unwrap(),
            "-signature", sig_file.path().to_str().unwrap(),
            msg_file.path().to_str().unwrap(),
        ])
        .output()
        .expect("openssl not found");

    assert!(
        output.status.success(),
        "openssl RSA-PSS verification failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}

// ---------------------------------------------------------------------------
// Test 2: ECDSA P-256 sign (with SHA-256) -> openssl verify
// ---------------------------------------------------------------------------

#[test]
fn ecdsa_sha256_sign_verified_by_openssl() {
    let entry = ec_entry();
    let msg = b"test message for ECDSA-SHA256";

    // CKM_ECDSA_SHA256: hash with SHA-256 internally, sign, return raw r||s (64 bytes per PKCS#11 s.2.3.1).
    let sig_raw = ops::sign(&entry, CKM_ECDSA_SHA256, msg).expect("ECDSA sign failed");
    assert_eq!(sig_raw.len(), 64, "CKM_ECDSA_SHA256 signature must be 64 bytes raw r||s");
    // openssl expects DER; convert from raw r||s using an independent implementation.
    let sig_der = raw_rs_to_der(&sig_raw);

    let sig_file = write_tmp(&sig_der);
    let msg_file = write_tmp(msg);
    let pub_file = write_tmp_str(EC_PUB_PEM);

    // openssl hashes msg with SHA-256 and verifies the ECDSA DER signature
    let output = Command::new("openssl")
        .args([
            "dgst", "-sha256",
            "-verify", pub_file.path().to_str().unwrap(),
            "-signature", sig_file.path().to_str().unwrap(),
            msg_file.path().to_str().unwrap(),
        ])
        .output()
        .expect("openssl not found");

    assert!(
        output.status.success(),
        "openssl ECDSA verification failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
}

// ---------------------------------------------------------------------------
// Test 3: wrong mechanism -> MechanismInvalid
// ---------------------------------------------------------------------------

#[test]
fn wrong_mechanism_returns_mechanism_invalid() {
    let entry = rsa_entry();
    // Use a mechanism that is not in ops::sign's match arms
    let bogus_mechanism = 0xDEAD_BEEF;
    match ops::sign(&entry, bogus_mechanism, b"data") {
        Err(OpsError::MechanismInvalid) => {}
        other => panic!("expected MechanismInvalid, got {:?}", other),
    }
}

// ---------------------------------------------------------------------------
// Test 4: key type mismatch -> KeyTypeInconsistent
// ---------------------------------------------------------------------------

#[test]
fn key_type_mismatch_returns_inconsistent() {
    // RSA mechanism with EC key
    let ec_entry = ec_entry();
    match ops::sign(&ec_entry, CKM_RSA_PKCS_PSS, b"data") {
        Err(OpsError::KeyTypeInconsistent) => {}
        other => panic!("expected KeyTypeInconsistent (RSA mech on EC key), got {:?}", other),
    }

    // EC mechanism with RSA key
    let rsa_entry = rsa_entry();
    match ops::sign(&rsa_entry, CKM_ECDSA_SHA256, b"data") {
        Err(OpsError::KeyTypeInconsistent) => {}
        other => panic!("expected KeyTypeInconsistent (EC mech on RSA key), got {:?}", other),
    }
}

// ---------------------------------------------------------------------------
// Test 5: CKM_ECDSA_SHA256 verify -- wolfcrypt signs, openssl validates the sig,
// then wolfcrypt verify must accept it.
//
// Oracle independence: wolfcrypt sign is independently verified against openssl
// in ecdsa_sha256_sign_verified_by_openssl above. Using that known-good signature
// to test verify exercises a different code path (wc_ecc_sign_hash !=
// wc_ecc_verify_hash) without being purely self-referential.
// ---------------------------------------------------------------------------

#[test]
fn ecdsa_sha256_verify_accepts_valid_signature() {
    let entry = ec_entry();
    let msg = b"test message for ECDSA-SHA256 verify";

    // Sign with wolfcrypt (CKM_ECDSA_SHA256 -- hashes internally, returns raw r||s).
    let sig = ops::sign(&entry, CKM_ECDSA_SHA256, msg).expect("ECDSA sign failed");

    // Verify: wolfcrypt verify must accept a raw r||s signature wolfcrypt produced.
    ops::verify(&entry, CKM_ECDSA_SHA256, msg, &sig)
        .expect("ECDSA-SHA256 verify rejected a valid signature");
}

// ---------------------------------------------------------------------------
// Test 6: CKM_ECDSA verify (prehash) -- wolfcrypt signs hash, wolfcrypt verifies.
// The sign path (sign_prehash) and verify path (verify_prehash) call different
// wolfCrypt C functions; consistency between them is a real correctness property.
// ---------------------------------------------------------------------------

#[test]
fn ecdsa_prehash_verify_accepts_valid_signature() {
    use std::process::Command;

    let entry = ec_entry();
    let msg = b"test message for ECDSA prehash verify";

    // Compute SHA-256(msg) using openssl as external oracle.
    let hash_hex = {
        let output = Command::new("openssl")
            .args(["dgst", "-sha256", "-hex"])
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::piped())
            .spawn()
            .expect("openssl not found");
        use std::io::Write;
        let mut child = output;
        child.stdin.take().unwrap().write_all(msg).unwrap();
        let out = child.wait_with_output().unwrap();
        assert!(out.status.success(), "openssl dgst failed");
        let s = String::from_utf8_lossy(&out.stdout);
        // output: "SHA2-256(stdin)= <hex>\n" or "(stdin)= <hex>\n"
        s.split_whitespace().last().unwrap().to_string()
    };
    let hash_bytes = hex::decode(&hash_hex).expect("hex decode of SHA-256");
    assert_eq!(hash_bytes.len(), 32, "SHA-256 must be 32 bytes");

    // Sign pre-hashed data with CKM_ECDSA -- returns raw r||s (64 bytes).
    let sig = ops::sign(&entry, CKM_ECDSA, &hash_bytes).expect("ECDSA prehash sign failed");

    // Verify the pre-hashed data against the raw r||s signature.
    ops::verify(&entry, CKM_ECDSA, &hash_bytes, &sig)
        .expect("ECDSA prehash verify rejected a valid signature");
}

// ---------------------------------------------------------------------------
// Test 7: tampered signature fails both ECDSA mechanisms.
// ---------------------------------------------------------------------------

#[test]
fn ecdsa_verify_rejects_tampered_signature() {
    let entry = ec_entry();
    let msg = b"message whose signature will be tampered";

    // Produce a valid CKM_ECDSA_SHA256 signature (raw r||s, 64 bytes).
    let mut sig = ops::sign(&entry, CKM_ECDSA_SHA256, msg).expect("sign");

    // Flip a byte in the middle of the raw r||s to produce an invalid signature.
    let mid = sig.len() / 2;
    sig[mid] ^= 0xFF;

    match ops::verify(&entry, CKM_ECDSA_SHA256, msg, &sig) {
        Err(OpsError::Crypto(_)) => {}
        other => panic!("expected Crypto error for tampered sig, got {:?}", other),
    }
}

// ---------------------------------------------------------------------------
// Test 8: verify key-type mismatch returns KeyTypeInconsistent.
// ---------------------------------------------------------------------------

#[test]
fn ecdsa_verify_key_type_mismatch() {
    let rsa_entry = rsa_entry();
    let ec_entry  = ec_entry();
    let dummy_sig = [0u8; 70];

    // ECDSA mechanism against RSA key.
    match ops::verify(&rsa_entry, CKM_ECDSA_SHA256, b"data", &dummy_sig) {
        Err(OpsError::KeyTypeInconsistent) => {}
        other => panic!("expected KeyTypeInconsistent, got {:?}", other),
    }

    // RSA mechanism against EC key.
    match ops::verify(&ec_entry, CKM_RSA_PKCS_PSS, b"data", &dummy_sig) {
        Err(OpsError::KeyTypeInconsistent) => {}
        other => panic!("expected KeyTypeInconsistent, got {:?}", other),
    }
}

// ---------------------------------------------------------------------------
// rs_to_der: multi-byte DER length encoding
// ---------------------------------------------------------------------------
//
// DER X.690 s.8.1.3: lengths >= 128 must use long-form encoding (0x81 prefix
// for 128-255 bytes). Passing 64-byte r/s (high bit set, requiring 0x00 pad)
// produces a SEQUENCE payload of 134 bytes -- which requires 0x81 0x86 in the
// length field. A 1-byte push of 0x86 would be parsed as INTEGER length by
// most DER parsers, producing invalid output.

#[test]
fn rs_to_der_long_form_sequence_length() {
    // 64-byte scalars: the 0x80 leading byte forces a 0x00 pad in each INTEGER.
    // Each encode_int output: [0x02, 0x41, 0x00, 0x80, 0x00 x 63] = 67 bytes.
    // Payload = 67 + 67 = 134 = 0x86. Requires long-form SEQUENCE length.
    let r = {
        let mut v = vec![0u8; 64];
        v[0] = 0x80;
        v
    };
    let s = r.clone();

    let der = ops::rs_to_der(&r, &s).expect("rs_to_der with non-empty scalars must not fail");

    // Verify SEQUENCE tag and long-form length prefix.
    assert_eq!(der[0], 0x30, "DER must start with SEQUENCE tag 0x30");
    assert_eq!(der[1], 0x81, "payload 134 requires long-form length 0x81 prefix");
    assert_eq!(der[2], 134,  "long-form length byte must be 134 (0x86)");

    // Each INTEGER: tag 0x02, length 0x41 (65), 0x00 pad, then 64 bytes.
    assert_eq!(der[3],  0x02, "first INTEGER tag");
    assert_eq!(der[4],  0x41, "first INTEGER length (65 bytes)");
    assert_eq!(der[5],  0x00, "first INTEGER must have 0x00 pad (high bit set)");
    assert_eq!(der[6],  0x80, "first INTEGER first data byte");

    let second_int_offset = 3 + 2 + 65; // tag + len + 65 content bytes
    assert_eq!(der[second_int_offset], 0x02, "second INTEGER tag");
    assert_eq!(der.len(), 3 + 134,  "total DER length must be tag(1) + long-len(2) + payload(134)");
}

#[test]
fn rs_to_der_short_form_p256() {
    // P-256 scalars: 32 bytes each. Maximum output per INTEGER = 35 bytes.
    // Maximum payload = 70 bytes < 128, so short-form length is correct.
    let r = {
        let mut v = vec![0u8; 32];
        v[0] = 0x80; // force 0x00 pad: int_len = 33, still short-form
        v
    };
    let s = vec![0x01u8; 32]; // no high bit: int_len = 32, no pad needed

    let der = ops::rs_to_der(&r, &s).expect("rs_to_der with non-empty scalars must not fail");

    assert_eq!(der[0], 0x30, "SEQUENCE tag");
    // payload < 128 -> short-form: second byte is the length directly
    assert!(der[1] < 0x80, "P-256 payload must use short-form length (< 0x80)");
}
