/// PKCS#11 cryptographic operations against key material loaded into the token.
///
/// Each function borrows a [`KeyEntry`] in-place; key bytes are never copied
/// outside the mlock'd allocation held by the Keystore.
use cryptoki_sys::{
    CK_MECHANISM_TYPE, CKM_ECDSA, CKM_ECDSA_SHA256, CKM_ML_DSA, CKM_ML_KEM,
    CKM_RSA_PKCS, CKM_RSA_PKCS_OAEP, CKM_RSA_PKCS_PSS,
};
use signature::{Signer as _, Verifier as _};
use wolfcrypt::{
    MlDsa65Signature, MlDsa65SigningKey, MlDsa65VerifyingKey,
    MlKem768DecapsulationKey, MlKem768EncapsulationKey,
    rsa::{RsaDigest, RsaPrivateKey},
    EcdsaCurve, P256, P256SigningKey,
};

use crate::keystore::{KeyEntry, KeyType};

/// Required prehash length for P-256 / CKM_ECDSA.
///
/// PKCS#11 s.11.11 (CKM_ECDSA): "The input to the C_Sign function is the
/// hash value generated by the hash algorithm used with the key." For P-256
/// the standard algorithm is SHA-256, producing exactly 32 bytes. Wolfcrypt's
/// `sign_prehash` accepts any length without erroring, but passing a wrong-
/// length hash produces an invalid (non-verifiable) signature -- we reject it
/// early to surface the caller error as CKR_DATA_LEN_RANGE.
const P256_HASH_LEN: usize = 32;

/// Byte length of a P-256 field element (group order = 256 bits = 32 bytes).
///
/// Used to split a raw r||s ECDSA signature into its two components.
/// Coincidentally equal to `P256_HASH_LEN` (SHA-256 also produces 32 bytes),
/// but the two constants serve different purposes: `P256_HASH_LEN` guards
/// the pre-hash input length; `P256_FIELD_LEN` indexes into the signature
/// byte array. (soft_PKCS11-5l26)
const P256_FIELD_LEN: usize = 32;

/// Fixed raw r||s signature length for P-256 per PKCS#11 s.2.3.1.
///
/// PKCS#11 s.2.3.1: "For the ECDSA mechanism ... the signature is the
/// concatenation of r and s, each of the same length as the base prime." For
/// P-256 (256-bit prime) each component is exactly 32 bytes -> 64 bytes total.
const P256_SIG_LEN: usize = 64;

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum OpsError {
    MechanismInvalid,
    KeyTypeInconsistent,
    /// The data length is wrong for the mechanism.
    ///
    /// `CKM_ECDSA` requires exactly `P256_HASH_LEN` (32) bytes -- the caller is
    /// responsible for hashing before calling `C_Sign`. Passing a SHA-1 (20-byte)
    /// or SHA-384 (48-byte) digest produces undefined wolfcrypt behavior; we reject
    /// it here and propagate as `CKR_DATA_LEN_RANGE` per PKCS#11 s.11.11.
    DataLenRange,
    Crypto(String),
}

// ---------------------------------------------------------------------------
// Public operations
// ---------------------------------------------------------------------------

/// Sign `data` with raw key material.
///
/// Note: `CKM_RSA_PKCS` is not in the advertised mechanism list (see lib.rs MECHANISMS)
/// because wolfcrypt's sign_pkcs1v15_with_digest double-hashes conformant callers.
/// The match arm below is kept for completeness but is unreachable from lib.rs.
///
/// For `CKM_ECDSA`, `data` is a pre-computed hash (exactly 32 bytes for P-256).
/// For `CKM_ECDSA_SHA256`, `data` is the raw message (hashed internally).
///
/// ECDSA signatures are returned as raw r||s per PKCS#11 s.2.3.1:
/// 32 bytes r followed by 32 bytes s, each zero-padded to the field size (P256_SIG_LEN = 64).
pub fn sign_raw(
    key_type: KeyType,
    der_bytes: &[u8],
    mechanism: CK_MECHANISM_TYPE,
    data: &[u8],
) -> Result<Vec<u8>, OpsError> {
    match mechanism {
        CKM_RSA_PKCS => {
            if key_type != KeyType::Rsa {
                return Err(OpsError::KeyTypeInconsistent);
            }
            let key = RsaPrivateKey::from_pkcs1_der(der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let sig = key
                .sign_pkcs1v15_with_digest(data, RsaDigest::Sha256)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            Ok(sig.as_ref().to_vec())
        }
        CKM_RSA_PKCS_PSS => {
            if key_type != KeyType::Rsa {
                return Err(OpsError::KeyTypeInconsistent);
            }
            let key = RsaPrivateKey::from_pkcs1_der(der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let sig = key
                .sign_pss_with_digest(data, RsaDigest::Sha256)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            Ok(sig.as_ref().to_vec())
        }
        CKM_ECDSA => {
            if key_type != KeyType::Ec {
                return Err(OpsError::KeyTypeInconsistent);
            }
            // `data` is a pre-computed hash. P-256 requires exactly 32 bytes
            // (SHA-256 output). Reject other lengths before calling sign_prehash:
            // wolfcrypt accepts any length silently but produces an invalid
            // (non-verifiable) signature for wrong-length input.
            if data.len() != P256_HASH_LEN {
                return Err(OpsError::DataLenRange);
            }
            let key = P256SigningKey::from_private_key_bytes(der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let sig = key
                .sign_prehash(data)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            // Return raw r||s per PKCS#11 s.2.3.1; wolfcrypt's EcdsaSignature
            // stores r||s internally (not DER) -- as_ref() returns those bytes.
            Ok(sig.as_ref().to_vec())
        }
        CKM_ECDSA_SHA256 => {
            if key_type != KeyType::Ec {
                return Err(OpsError::KeyTypeInconsistent);
            }
            let key = P256SigningKey::from_private_key_bytes(der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let hash = P256::hash_message(data)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let sig = key
                .sign_prehash(&hash)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            // Return raw r||s per PKCS#11 s.2.3.1.
            Ok(sig.as_ref().to_vec())
        }
        _ => Err(OpsError::MechanismInvalid),
    }
}

/// Sign `data` with the key in `key_entry` using the given PKCS#11 mechanism.
pub fn sign(
    key_entry: &KeyEntry,
    mechanism: CK_MECHANISM_TYPE,
    data: &[u8],
) -> Result<Vec<u8>, OpsError> {
    if mechanism == CKM_ML_DSA {
        if key_entry.key_type != KeyType::MlDsa65 {
            return Err(OpsError::KeyTypeInconsistent);
        }
        let pub_bytes = key_entry.pub_bytes.as_deref()
            .ok_or_else(|| OpsError::Crypto("ML-DSA-65 key missing public bytes".to_string()))?;
        let sk = MlDsa65SigningKey::from_key_bytes(&key_entry.der_bytes, pub_bytes)
            .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
        let sig: MlDsa65Signature = sk.try_sign(data)
            .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
        return Ok(sig.as_ref().to_vec());
    }
    sign_raw(key_entry.key_type, &key_entry.der_bytes, mechanism, data)
}

/// Verify `signature` over `data` with the public key derived from `key_entry`.
pub fn verify(
    key_entry: &KeyEntry,
    mechanism: CK_MECHANISM_TYPE,
    data: &[u8],
    signature: &[u8],
) -> Result<(), OpsError> {
    if mechanism == CKM_ML_DSA {
        if key_entry.key_type != KeyType::MlDsa65 {
            return Err(OpsError::KeyTypeInconsistent);
        }
        let pub_bytes = key_entry.pub_bytes.as_deref()
            .ok_or_else(|| OpsError::Crypto("ML-DSA-65 key missing public bytes".to_string()))?;
        let vk = MlDsa65VerifyingKey::from_bytes(pub_bytes)
            .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
        let sig = MlDsa65Signature::try_from(signature)
            .map_err(|_| OpsError::Crypto("invalid ML-DSA-65 signature length".to_string()))?;
        return vk.verify(data, &sig)
            .map_err(|_| OpsError::Crypto("ML-DSA-65 verify failed".to_string()));
    }
    match mechanism {
        CKM_RSA_PKCS => {
            if key_entry.key_type != KeyType::Rsa {
                return Err(OpsError::KeyTypeInconsistent);
            }
            let key = RsaPrivateKey::from_pkcs1_der(&key_entry.der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let pub_key = key.public_key();
            let sig = wolfcrypt::rsa::RsaPkcs1v15Signature::try_from(signature)
                .map_err(|_| OpsError::Crypto("invalid RSA PKCS#1v1.5 signature bytes".to_string()))?;
            pub_key
                .verify_pkcs1v15_with_digest(data, &sig, RsaDigest::Sha256)
                .map_err(|_| OpsError::Crypto("RSA PKCS#1v1.5 verify failed".to_string()))
        }
        CKM_RSA_PKCS_PSS => {
            if key_entry.key_type != KeyType::Rsa {
                return Err(OpsError::KeyTypeInconsistent);
            }
            let key = RsaPrivateKey::from_pkcs1_der(&key_entry.der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let pub_key = key.public_key();
            let sig = wolfcrypt::rsa::RsaPssSignature::try_from(signature)
                .map_err(|_| OpsError::Crypto("invalid RSA-PSS signature bytes".to_string()))?;
            pub_key
                .verify_pss_with_digest(data, &sig, RsaDigest::Sha256)
                .map_err(|_| OpsError::Crypto("RSA-PSS verify failed".to_string()))
        }
        CKM_ECDSA => {
            // PKCS#11 s.2.3.1: `signature` is raw r||s bytes -- P256_SIG_LEN = 64
            // bytes for P-256 (32 bytes r followed by 32 bytes s, zero-padded).
            // wolfcrypt's verify_prehash expects DER; convert here.
            if key_entry.key_type != KeyType::Ec {
                return Err(OpsError::KeyTypeInconsistent);
            }
            // Reject wrong-length prehash for the same reason as in sign().
            if data.len() != P256_HASH_LEN {
                return Err(OpsError::DataLenRange);
            }
            if signature.len() != P256_SIG_LEN {
                return Err(OpsError::Crypto(format!(
                    "CKM_ECDSA signature must be {P256_SIG_LEN} bytes (raw r||s), got {}",
                    signature.len()
                )));
            }
            let sig_der = rs_to_der(&signature[..P256_FIELD_LEN], &signature[P256_FIELD_LEN..])?;
            let key = P256SigningKey::from_private_key_bytes(&key_entry.der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let pub_key = key.verifying_key()
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            pub_key
                .verify_prehash(data, &sig_der)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))
        }
        CKM_ECDSA_SHA256 => {
            // PKCS#11 s.2.3.1: `signature` is raw r||s bytes (same as CKM_ECDSA).
            // data is the raw message; hash internally then verify against DER sig.
            if key_entry.key_type != KeyType::Ec {
                return Err(OpsError::KeyTypeInconsistent);
            }
            if signature.len() != P256_SIG_LEN {
                return Err(OpsError::Crypto(format!(
                    "CKM_ECDSA_SHA256 signature must be {P256_SIG_LEN} bytes (raw r||s), got {}",
                    signature.len()
                )));
            }
            let sig_der = rs_to_der(&signature[..P256_FIELD_LEN], &signature[P256_FIELD_LEN..])?;
            let hash = P256::hash_message(data)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let key = P256SigningKey::from_private_key_bytes(&key_entry.der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let pub_key = key.verifying_key()
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            pub_key
                .verify_prehash(&hash, &sig_der)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))
        }
        _ => Err(OpsError::MechanismInvalid),
    }
}

/// Encrypt `plaintext` using the public key in `key_entry`.
///
/// For `CKM_ML_KEM`, `plaintext` is unused -- encapsulation generates a fresh
/// random shared secret. The output is `ciphertext || shared_secret` (ML-KEM
/// ciphertext size + 32 bytes). The caller sends the ciphertext portion to the
/// decapsulating party; both parties derive the same shared secret.
pub fn encrypt(
    key_entry: &KeyEntry,
    mechanism: CK_MECHANISM_TYPE,
    plaintext: &[u8],
) -> Result<Vec<u8>, OpsError> {
    match mechanism {
        CKM_RSA_PKCS_OAEP => {
            if key_entry.key_type != KeyType::Rsa {
                return Err(OpsError::KeyTypeInconsistent);
            }
            let key = RsaPrivateKey::from_pkcs1_der(&key_entry.der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let pub_key = key.public_key();
            pub_key
                .encrypt_oaep(plaintext)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))
        }
        CKM_ML_KEM => {
            let _ = plaintext;
            if key_entry.key_type != KeyType::MlKem768 {
                return Err(OpsError::KeyTypeInconsistent);
            }
            let pub_bytes = key_entry.pub_bytes.as_deref()
                .ok_or_else(|| OpsError::Crypto("ML-KEM-768 key missing public bytes".to_string()))?;
            let mut ek = MlKem768EncapsulationKey::from_bytes(pub_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let (ct, ss) = ek.encapsulate()
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let mut out = ct;
            out.extend_from_slice(ss.as_bytes());
            Ok(out)
        }
        _ => Err(OpsError::MechanismInvalid),
    }
}

/// Decrypt `ciphertext` using the private key in `key_entry`.
///
/// For `CKM_ML_KEM`, `ciphertext` must be exactly the ML-KEM-768 ciphertext
/// (1088 bytes). Returns the 32-byte shared secret.
pub fn decrypt(
    key_entry: &KeyEntry,
    mechanism: CK_MECHANISM_TYPE,
    ciphertext: &[u8],
) -> Result<Vec<u8>, OpsError> {
    match mechanism {
        CKM_RSA_PKCS_OAEP => {
            if key_entry.key_type != KeyType::Rsa {
                return Err(OpsError::KeyTypeInconsistent);
            }
            let key = RsaPrivateKey::from_pkcs1_der(&key_entry.der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            key.decrypt_oaep(ciphertext)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))
        }
        CKM_ML_KEM => {
            if key_entry.key_type != KeyType::MlKem768 {
                return Err(OpsError::KeyTypeInconsistent);
            }
            // FIPS 203 s.6.3: ML-KEM-768 ciphertext is exactly 1088 bytes.
            // Reject before calling native code; some wolfcrypt builds do not
            // validate length internally and may read past the buffer end.
            const ML_KEM_768_CIPHERTEXT_LEN: usize = 1088;
            if ciphertext.len() != ML_KEM_768_CIPHERTEXT_LEN {
                return Err(OpsError::DataLenRange);
            }
            let dk = MlKem768DecapsulationKey::from_private_bytes(&key_entry.der_bytes)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            let ss = dk.decapsulate(ciphertext)
                .map_err(|e| OpsError::Crypto(format!("{e:?}")))?;
            Ok(ss.as_bytes().to_vec())
        }
        _ => Err(OpsError::MechanismInvalid),
    }
}

// ---------------------------------------------------------------------------
// DER encoding for ECDSA signatures
// ---------------------------------------------------------------------------

/// Encode an ECDSA (r, s) scalar pair as a DER SEQUENCE { INTEGER r, INTEGER s }.
///
/// Uses multi-byte DER length encoding (X.690 s.8.1.3) for any payload size.
/// Short-form (1 byte) is valid only for lengths 0-127; larger values require a
/// long-form prefix (0x81 for 128-255, 0x82 for 256-65535). P-256 and P-384
/// always produce short-form SEQUENCE payloads; P-521's payload is 138 bytes and
/// requires long-form -- a naive single-byte push would silently produce invalid
/// DER that signature parsers reject without a clear error.
///
/// Returns `Err(OpsError::Crypto)` if either component is empty. Wolfcrypt always
/// returns fixed-size non-empty scalars (P-256: 32 bytes each), so this path is
/// unreachable in practice -- but returning an error is safe across the PKCS#11
/// FFI boundary, whereas a panic is undefined behaviour.
pub fn rs_to_der(r: &[u8], s: &[u8]) -> Result<Vec<u8>, OpsError> {
    /// X.690 s.8.1.3 definite-length encoding.
    fn der_len(n: usize) -> Vec<u8> {
        if n < 0x80 {
            vec![n as u8]
        } else if n < 0x100 {
            vec![0x81, n as u8]
        } else {
            // Handles up to 65535 bytes -- sufficient for any practical elliptic curve.
            vec![0x82, (n >> 8) as u8, (n & 0xFF) as u8]
        }
    }

    /// Encode a single DER INTEGER from an unsigned big-endian byte slice.
    ///
    /// Returns `None` if `n` is empty. Wolfcrypt never returns empty components,
    /// but we cannot panic across FFI so we return an error instead.
    fn encode_int(n: &[u8]) -> Option<Vec<u8>> {
        if n.is_empty() {
            // Empty scalar is never produced by wolfcrypt, but would cause
            // usize::MAX underflow in the unwrap_or path -- return None so
            // the caller can propagate an OpsError rather than panic.
            return None;
        }
        // Strip leading zero bytes but keep at least one byte (index n.len()-1
        // is safe here because we checked n.is_empty() above).
        let trimmed: &[u8] = &n[n.iter().position(|&b| b != 0).unwrap_or(n.len() - 1)..];
        // Prepend 0x00 if the high bit is set (DER requires non-negative integers).
        let needs_pad = trimmed[0] & 0x80 != 0;
        let int_len = trimmed.len() + usize::from(needs_pad);
        let mut out = vec![0x02]; // INTEGER tag
        out.extend(der_len(int_len));
        if needs_pad {
            out.push(0x00);
        }
        out.extend_from_slice(trimmed);
        Some(out)
    }

    let r_enc = encode_int(r)
        .ok_or_else(|| OpsError::Crypto("ECDSA r component is empty".to_string()))?;
    let s_enc = encode_int(s)
        .ok_or_else(|| OpsError::Crypto("ECDSA s component is empty".to_string()))?;
    let payload = r_enc.len() + s_enc.len();
    let mut der = vec![0x30]; // SEQUENCE tag
    der.extend(der_len(payload));
    der.extend(r_enc);
    der.extend(s_enc);
    Ok(der)
}
